# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'formrZQXNo.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtOpenGLWidgets import QOpenGLWidget
from PySide6.QtWidgets import (QApplication, QLCDNumber, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QSlider, QStackedWidget,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(480, 640)
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        Form.setFont(font)
        self.pagelayoutwidget = QStackedWidget(Form)
        self.pagelayoutwidget.setObjectName(u"pagelayoutwidget")
        self.pagelayoutwidget.setGeometry(QRect(0, 70, 480, 560))
        self.start_page = QWidget()
        self.start_page.setObjectName(u"start_page")
        self.continue_btn = QPushButton(self.start_page)
        self.continue_btn.setObjectName(u"continue_btn")
        self.continue_btn.setGeometry(QRect(10, 290, 221, 170))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(30)
        self.continue_btn.setFont(font1)
        self.clockdisplay = QLCDNumber(self.start_page)
        self.clockdisplay.setObjectName(u"clockdisplay")
        self.clockdisplay.setGeometry(QRect(0, 20, 480, 100))
        self.clockdisplay.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.sensordisplay_1 = QLCDNumber(self.start_page)
        self.sensordisplay_1.setObjectName(u"sensordisplay_1")
        self.sensordisplay_1.setGeometry(QRect(0, 150, 230, 100))
        self.sensordisplay_1.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.clockdisplay_label = QLabel(self.start_page)
        self.clockdisplay_label.setObjectName(u"clockdisplay_label")
        self.clockdisplay_label.setGeometry(QRect(210, 130, 49, 15))
        font2 = QFont()
        font2.setFamilies([u"Consolas"])
        font2.setBold(True)
        self.clockdisplay_label.setFont(font2)
        self.sensordisplay_1_label = QLabel(self.start_page)
        self.sensordisplay_1_label.setObjectName(u"sensordisplay_1_label")
        self.sensordisplay_1_label.setGeometry(QRect(90, 260, 49, 15))
        font3 = QFont()
        font3.setFamilies([u"Comic Sans MS"])
        font3.setBold(True)
        self.sensordisplay_1_label.setFont(font3)
        self.close_btn = QPushButton(self.start_page)
        self.close_btn.setObjectName(u"close_btn")
        self.close_btn.setGeometry(QRect(240, 290, 221, 170))
        self.close_btn.setFont(font1)
        self.sensordisplay_2 = QLCDNumber(self.start_page)
        self.sensordisplay_2.setObjectName(u"sensordisplay_2")
        self.sensordisplay_2.setGeometry(QRect(250, 150, 230, 100))
        self.sensordisplay_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.sensordisplay_1_label_2 = QLabel(self.start_page)
        self.sensordisplay_1_label_2.setObjectName(u"sensordisplay_1_label_2")
        self.sensordisplay_1_label_2.setGeometry(QRect(350, 260, 49, 15))
        self.sensordisplay_1_label_2.setFont(font3)
        self.pagelayoutwidget.addWidget(self.start_page)
        self.mainmenu_page = QWidget()
        self.mainmenu_page.setObjectName(u"mainmenu_page")
        self.systeminfo_page_btn = QPushButton(self.mainmenu_page)
        self.systeminfo_page_btn.setObjectName(u"systeminfo_page_btn")
        self.systeminfo_page_btn.setGeometry(QRect(10, 10, 201, 151))
        font4 = QFont()
        font4.setFamilies([u"Segoe UI"])
        font4.setPointSize(20)
        self.systeminfo_page_btn.setFont(font4)
        self.editsettings_page_btn = QPushButton(self.mainmenu_page)
        self.editsettings_page_btn.setObjectName(u"editsettings_page_btn")
        self.editsettings_page_btn.setGeometry(QRect(270, 10, 201, 151))
        self.editsettings_page_btn.setFont(font4)
        self.mainmenu_back_btn = QPushButton(self.mainmenu_page)
        self.mainmenu_back_btn.setObjectName(u"mainmenu_back_btn")
        self.mainmenu_back_btn.setGeometry(QRect(10, 310, 201, 151))
        font5 = QFont()
        font5.setFamilies([u"Segoe UI"])
        font5.setPointSize(25)
        self.mainmenu_back_btn.setFont(font5)
        self.manualcontrols_page_btn = QPushButton(self.mainmenu_page)
        self.manualcontrols_page_btn.setObjectName(u"manualcontrols_page_btn")
        self.manualcontrols_page_btn.setGeometry(QRect(10, 160, 201, 151))
        font6 = QFont()
        font6.setFamilies([u"Segoe UI"])
        font6.setPointSize(18)
        self.manualcontrols_page_btn.setFont(font6)
        self.monitordata_page_btn = QPushButton(self.mainmenu_page)
        self.monitordata_page_btn.setObjectName(u"monitordata_page_btn")
        self.monitordata_page_btn.setGeometry(QRect(270, 160, 201, 151))
        self.monitordata_page_btn.setFont(font4)
        self.pagelayoutwidget.addWidget(self.mainmenu_page)
        self.monitordata_page = QWidget()
        self.monitordata_page.setObjectName(u"monitordata_page")
        self.monitordata_back_btn = QPushButton(self.monitordata_page)
        self.monitordata_back_btn.setObjectName(u"monitordata_back_btn")
        self.monitordata_back_btn.setGeometry(QRect(250, 360, 201, 151))
        self.monitordata_back_btn.setFont(font5)
        self.pagelayoutwidget.addWidget(self.monitordata_page)
        self.manualcontrols_page = QWidget()
        self.manualcontrols_page.setObjectName(u"manualcontrols_page")
        self.waternow_btn = QPushButton(self.manualcontrols_page)
        self.waternow_btn.setObjectName(u"waternow_btn")
        self.waternow_btn.setGeometry(QRect(10, 10, 201, 151))
        self.waternow_btn.setFont(font4)
        self.lightswitch_btn = QPushButton(self.manualcontrols_page)
        self.lightswitch_btn.setObjectName(u"lightswitch_btn")
        self.lightswitch_btn.setGeometry(QRect(270, 10, 201, 151))
        self.lightswitch_btn.setFont(font4)
        self.fanon_btn = QPushButton(self.manualcontrols_page)
        self.fanon_btn.setObjectName(u"fanon_btn")
        self.fanon_btn.setGeometry(QRect(10, 160, 201, 151))
        self.fanon_btn.setFont(font4)
        self.takepicture_btn = QPushButton(self.manualcontrols_page)
        self.takepicture_btn.setObjectName(u"takepicture_btn")
        self.takepicture_btn.setGeometry(QRect(270, 160, 201, 151))
        self.takepicture_btn.setFont(font4)
        self.recorddata_btn = QPushButton(self.manualcontrols_page)
        self.recorddata_btn.setObjectName(u"recorddata_btn")
        self.recorddata_btn.setGeometry(QRect(10, 310, 201, 151))
        self.recorddata_btn.setFont(font4)
        self.manualcontrols_back_btn = QPushButton(self.manualcontrols_page)
        self.manualcontrols_back_btn.setObjectName(u"manualcontrols_back_btn")
        self.manualcontrols_back_btn.setGeometry(QRect(270, 310, 201, 151))
        self.manualcontrols_back_btn.setFont(font4)
        self.pagelayoutwidget.addWidget(self.manualcontrols_page)
        self.systeminfo_page = QWidget()
        self.systeminfo_page.setObjectName(u"systeminfo_page")
        self.updatefirmware_page_btn = QPushButton(self.systeminfo_page)
        self.updatefirmware_page_btn.setObjectName(u"updatefirmware_page_btn")
        self.updatefirmware_page_btn.setGeometry(QRect(10, 10, 201, 151))
        self.updatefirmware_page_btn.setFont(font6)
        self.logexport_page_btn = QPushButton(self.systeminfo_page)
        self.logexport_page_btn.setObjectName(u"logexport_page_btn")
        self.logexport_page_btn.setGeometry(QRect(270, 10, 201, 151))
        self.logexport_page_btn.setFont(font4)
        self.systeminfo_back_btn = QPushButton(self.systeminfo_page)
        self.systeminfo_back_btn.setObjectName(u"systeminfo_back_btn")
        self.systeminfo_back_btn.setGeometry(QRect(10, 160, 201, 151))
        self.systeminfo_back_btn.setFont(font4)
        self.systemversion_label = QLabel(self.systeminfo_page)
        self.systemversion_label.setObjectName(u"systemversion_label")
        self.systemversion_label.setGeometry(QRect(10, 320, 451, 61))
        font7 = QFont()
        font7.setFamilies([u"Segoe UI"])
        font7.setPointSize(17)
        self.systemversion_label.setFont(font7)
        self.pagelayoutwidget.addWidget(self.systeminfo_page)
        self.editsettings_page = QWidget()
        self.editsettings_page.setObjectName(u"editsettings_page")
        self.irrigation_page_btn = QPushButton(self.editsettings_page)
        self.irrigation_page_btn.setObjectName(u"irrigation_page_btn")
        self.irrigation_page_btn.setGeometry(QRect(270, 10, 201, 151))
        self.irrigation_page_btn.setFont(font5)
        self.editsettings_back_btn = QPushButton(self.editsettings_page)
        self.editsettings_back_btn.setObjectName(u"editsettings_back_btn")
        self.editsettings_back_btn.setGeometry(QRect(270, 160, 201, 151))
        self.editsettings_back_btn.setFont(font5)
        self.datetime_page_btn = QPushButton(self.editsettings_page)
        self.datetime_page_btn.setObjectName(u"datetime_page_btn")
        self.datetime_page_btn.setGeometry(QRect(10, 10, 201, 151))
        self.datetime_page_btn.setFont(font5)
        self.cameratoggle_btn = QPushButton(self.editsettings_page)
        self.cameratoggle_btn.setObjectName(u"cameratoggle_btn")
        self.cameratoggle_btn.setGeometry(QRect(10, 160, 201, 151))
        self.cameratoggle_btn.setFont(font6)
        self.cameratoggle_btn.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.brightness_slider = QSlider(self.editsettings_page)
        self.brightness_slider.setObjectName(u"brightness_slider")
        self.brightness_slider.setGeometry(QRect(20, 330, 441, 51))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightness_slider.sizePolicy().hasHeightForWidth())
        self.brightness_slider.setSizePolicy(sizePolicy)
        font8 = QFont()
        font8.setFamilies([u"Segoe UI"])
        font8.setPointSize(10)
        self.brightness_slider.setFont(font8)
        self.brightness_slider.setMinimum(25)
        self.brightness_slider.setMaximum(255)
        self.brightness_slider.setValue(150)
        self.brightness_slider.setOrientation(Qt.Orientation.Horizontal)
        self.brightness_slider.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.brightness_slider.setTickInterval(10)
        self.brightness_label = QLabel(self.editsettings_page)
        self.brightness_label.setObjectName(u"brightness_label")
        self.brightness_label.setGeometry(QRect(140, 380, 201, 61))
        font9 = QFont()
        font9.setFamilies([u"Segoe UI"])
        font9.setPointSize(20)
        font9.setBold(False)
        self.brightness_label.setFont(font9)
        self.pagelayoutwidget.addWidget(self.editsettings_page)
        self.datetime_page = QWidget()
        self.datetime_page.setObjectName(u"datetime_page")
        self.datetime_back_btn = QPushButton(self.datetime_page)
        self.datetime_back_btn.setObjectName(u"datetime_back_btn")
        self.datetime_back_btn.setGeometry(QRect(260, 470, 201, 151))
        self.datetime_back_btn.setFont(font5)
        self.minus_btn = QPushButton(self.datetime_page)
        self.minus_btn.setObjectName(u"minus_btn")
        self.minus_btn.setGeometry(QRect(270, 250, 81, 81))
        self.minus_btn.setFont(font1)
        self.plus_btn = QPushButton(self.datetime_page)
        self.plus_btn.setObjectName(u"plus_btn")
        self.plus_btn.setGeometry(QRect(170, 250, 81, 81))
        self.plus_btn.setFont(font1)
        self.datetimenumber = QLineEdit(self.datetime_page)
        self.datetimenumber.setObjectName(u"datetimenumber")
        self.datetimenumber.setGeometry(QRect(50, 120, 381, 111))
        font10 = QFont()
        font10.setFamilies([u"Segoe UI"])
        font10.setPointSize(25)
        font10.setBold(True)
        self.datetimenumber.setFont(font10)
        self.datetimenumber.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.verticalSlider = QSlider(self.datetime_page)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(40, 440, 61, 160))
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider.setTickPosition(QSlider.TickPosition.TicksBothSides)
        self.verticalSlider.setTickInterval(20)
        self.pagelayoutwidget.addWidget(self.datetime_page)
        self.irrigation_page = QWidget()
        self.irrigation_page.setObjectName(u"irrigation_page")
        self.humidset_page_btn = QPushButton(self.irrigation_page)
        self.humidset_page_btn.setObjectName(u"humidset_page_btn")
        self.humidset_page_btn.setGeometry(QRect(10, 10, 201, 151))
        self.humidset_page_btn.setFont(font5)
        self.irrigation_back_btn = QPushButton(self.irrigation_page)
        self.irrigation_back_btn.setObjectName(u"irrigation_back_btn")
        self.irrigation_back_btn.setGeometry(QRect(270, 10, 201, 151))
        self.irrigation_back_btn.setFont(font5)
        self.pagelayoutwidget.addWidget(self.irrigation_page)
        self.humidset_page = QWidget()
        self.humidset_page.setObjectName(u"humidset_page")
        self.openGLWidget = QOpenGLWidget(self.humidset_page)
        self.openGLWidget.setObjectName(u"openGLWidget")
        self.openGLWidget.setGeometry(QRect(70, 150, 300, 200))
        self.humidset_back_btn = QPushButton(self.humidset_page)
        self.humidset_back_btn.setObjectName(u"humidset_back_btn")
        self.humidset_back_btn.setGeometry(QRect(250, 360, 201, 151))
        self.humidset_back_btn.setFont(font5)
        self.pagelayoutwidget.addWidget(self.humidset_page)
        self.statusbar = QWidget(Form)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setGeometry(QRect(0, 0, 480, 80))
        self.statusbar.setStyleSheet(u"background-color: gray\n"
"")
        self.statusbar_label = QLabel(self.statusbar)
        self.statusbar_label.setObjectName(u"statusbar_label")
        self.statusbar_label.setGeometry(QRect(20, 10, 441, 61))
        self.statusbar_label.setFont(font8)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.continue_btn.setText(QCoreApplication.translate("Form", u"Continue", None))
        self.clockdisplay_label.setText(QCoreApplication.translate("Form", u"Clock", None))
        self.sensordisplay_1_label.setText(QCoreApplication.translate("Form", u"sensor 1", None))
        self.close_btn.setText(QCoreApplication.translate("Form", u"Close", None))
        self.sensordisplay_1_label_2.setText(QCoreApplication.translate("Form", u"sensor 2", None))
        self.systeminfo_page_btn.setText(QCoreApplication.translate("Form", u"System Info", None))
        self.editsettings_page_btn.setText(QCoreApplication.translate("Form", u"Edit Settings", None))
        self.mainmenu_back_btn.setText(QCoreApplication.translate("Form", u"Back", None))
        self.manualcontrols_page_btn.setText(QCoreApplication.translate("Form", u"Manual Controls", None))
        self.monitordata_page_btn.setText(QCoreApplication.translate("Form", u"Monitor Data", None))
        self.monitordata_back_btn.setText(QCoreApplication.translate("Form", u"Back", None))
        self.waternow_btn.setText(QCoreApplication.translate("Form", u"Water Now", None))
        self.lightswitch_btn.setText(QCoreApplication.translate("Form", u"Light Switch", None))
        self.fanon_btn.setText(QCoreApplication.translate("Form", u"Fan On", None))
        self.takepicture_btn.setText(QCoreApplication.translate("Form", u"Take Picture", None))
        self.recorddata_btn.setText(QCoreApplication.translate("Form", u"Record Data", None))
        self.manualcontrols_back_btn.setText(QCoreApplication.translate("Form", u"Back", None))
        self.updatefirmware_page_btn.setText(QCoreApplication.translate("Form", u"Update Firmware", None))
        self.logexport_page_btn.setText(QCoreApplication.translate("Form", u"Log Export", None))
        self.systeminfo_back_btn.setText(QCoreApplication.translate("Form", u"Back", None))
        self.systemversion_label.setText(QCoreApplication.translate("Form", u"<<System Version>>", None))
        self.irrigation_page_btn.setText(QCoreApplication.translate("Form", u"Irrigation", None))
        self.editsettings_back_btn.setText(QCoreApplication.translate("Form", u"Back", None))
        self.datetime_page_btn.setText(QCoreApplication.translate("Form", u"Date/Time", None))
        self.cameratoggle_btn.setText(QCoreApplication.translate("Form", u"Camera Toggle", None))
        self.brightness_label.setText(QCoreApplication.translate("Form", u"<<Brightness>>", None))
        self.datetime_back_btn.setText(QCoreApplication.translate("Form", u"Back", None))
        self.minus_btn.setText(QCoreApplication.translate("Form", u"-", None))
        self.plus_btn.setText(QCoreApplication.translate("Form", u"+", None))
        self.datetimenumber.setInputMask("")
        self.datetimenumber.setText("")
        self.datetimenumber.setPlaceholderText(QCoreApplication.translate("Form", u"0", None))
        self.humidset_page_btn.setText(QCoreApplication.translate("Form", u"Humid Set", None))
        self.irrigation_back_btn.setText(QCoreApplication.translate("Form", u"Back", None))
        self.humidset_back_btn.setText(QCoreApplication.translate("Form", u"Back", None))
        self.statusbar_label.setText(QCoreApplication.translate("Form", u"<<Status Bar>> ", None))
    # retranslateUi

